version: '3.1'
services:
  api:
    build:
      context: .
    command: npm run start
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"

  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  redis:
    image: redis:latest
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@db:${DB_PORT}/
      ME_CONFIG_BASICAUTH: null

